### ISSUE TITLE
Embed gif lages phones on discord

### ISSUE THREAD

**Issue by alec-jensen** [xpple/dontasktoa.sk#3]
Whenever I use the embed gif on discord, it lags my phone immensely. I have a samsung Galaxy note 8

**Comment by xpple** [comment]
Strange, I thought Discord compressed the images to reduce fill size...

**Comment by xpple** [comment]
I have heard this problem before though, I think I'll reduce the quality of the gif a bit.

**Comment by xpple** [comment]
I have lowered the quality slightly. Feel free to re-open this issue if the embed still lags your phone.
